stages:
  - checks

sanity-checks:
  stage: checks
  image: registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/sanity-checks:latest
  script: "c/check.py"

.branch-compile-check: &branch-compile-check
  stage: checks
  except: 
    refs:
      - master
  script:
    - "${CC} -v --version"
    - "./scripts/diff_build.sh"

.clang-3-9: &clang-3-9
  image: registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/clang:3.9
  variables:
    CC: clang-3.9

.gcc-5: &gcc-5
  image: registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/gcc:5
  variables:
    CC: gcc-5 
    
branch-compile-clang:3.9:
  <<: *branch-compile-check
  <<: *clang-3-9

branch-compile-gcc:5:
  <<: *branch-compile-check
  <<: *gcc-5

.master-compile-check: &master-compile-check
  stage: checks
  only: 
    refs:
      - master
  script:
    - "${CC} -v --version"
    - "cd c"
    - "make -j2"
    
.master-compile-check-juliet: &master-compile-check-juliet
  stage: checks
  only: 
    refs:
      - master
  script:
    - "${CC} -v --version"
    - "cd c/Juliet_Test"
    - "make -j2"    

master-compile-clang:3.9:
  <<: *master-compile-check
  <<: *clang-3-9

master-compile-gcc:5:
  <<: *master-compile-check
  <<: *gcc-5    
    
master-compile-clang:3.9-juliet:
  <<: *master-compile-check-juliet
  <<: *clang-3-9

master-compile-gcc:5-juliet:
  <<: *master-compile-check-juliet
  <<: *gcc-5

preprocessing-consistency:
  stage: checks
  image: registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/preprocessing-consistency:latest
  script:
    - "goto-diff --version"
    - "cd c"
    - "./compare.py --keep-going --skip-large"

java:
  stage: checks
  image: registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/java:latest
  script:
      # unset variables to not leak their content through result files
    - "unset $(compgen -v CI) $(compgen -v GIT)"
    - "java/check-compile.sh"
  artifacts:
    paths:
      - "java/results/*logfiles*"
      - "java/results/*.results.Werror.xml*"
      - "java/results/*.html"
    when: always
